### ISSUE TITLE
Python error when closing QGIS

### ISSUE THREAD

**Issue by Gustry** [gkahiu/qrbarcodeitem-plugin#2]
Very very frequent Python error I have when I quit QGIS : 

```
Erreur lors du déchargement de l'extension qrbarcodeitem 

KeyError: 'qrbarcodeitem' 
Traceback (most recent call last):
  File "/home/etienne/dev/app/qgis-ltr/share/qgis/python/qgis/utils.py", line 437, in unloadPlugin
    _unloadPluginModules(packageName)
  File "/home/etienne/dev/app/qgis-ltr/share/qgis/python/qgis/utils.py", line 466, in _unloadPluginModules
    for path in sys.modules[mod].__path__:
  File "", line 1174, in __iter__
  File "", line 1162, in _recalculate
  File "", line 1158, in _get_parent_path
KeyError: 'qrbarcodeitem'
```

I'm not sure how to fix it. Maybe the plugin isn't loading/unloading properly ?

Is-it only me ?

**Comment by gkahiu** [comment]
You are the first to report but nonetheless still worth to investigate. In which version of the plugin are you experiencing this? 

Not sure whether its related but I introduced cleanup functionality when unloading the plugin in version 0.2. To confirm, could you try comment [this](https://github.com/gkahiu/qrbarcodeitem-plugin/blob/master/qrbarcodeitem/plugin.py#L92) line and see whether you still get this error?

**Comment by Gustry** [comment]
The latest available in the plugin manager.

Strange that it's only me.
